apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: postfix
    app.kubernetes.io/component: postfix
    app.kubernetes.io/instance: postfix
    app.kubernetes.io/name: postfix
  name: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: postfix
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: postfix
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/postfix/postfix:latest
        imagePullPolicy: Always
        name: postfix
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      serviceAccount: postfix
